set(_CATKIN_CURRENT_PACKAGE "my_robot_description")
set(my_robot_description_VERSION "0.0.1")
set(my_robot_description_MAINTAINER "Your Name <your@email.com>")
set(my_robot_description_PACKAGE_FORMAT "2")
set(my_robot_description_BUILD_DEPENDS "rospy" "roscpp" "std_msgs" "rviz" "robot_state_publisher" "joint_state_publisher" "tf")
set(my_robot_description_BUILD_EXPORT_DEPENDS "rospy" "roscpp" "std_msgs" "rviz" "robot_state_publisher" "joint_state_publisher" "tf")
set(my_robot_description_BUILDTOOL_DEPENDS "catkin")
set(my_robot_description_BUILDTOOL_EXPORT_DEPENDS )
set(my_robot_description_EXEC_DEPENDS "rospy" "roscpp" "std_msgs" "rviz" "robot_state_publisher" "joint_state_publisher" "tf")
set(my_robot_description_RUN_DEPENDS "rospy" "roscpp" "std_msgs" "rviz" "robot_state_publisher" "joint_state_publisher" "tf")
set(my_robot_description_TEST_DEPENDS )
set(my_robot_description_DOC_DEPENDS )
set(my_robot_description_URL_WEBSITE "")
set(my_robot_description_URL_BUGTRACKER "")
set(my_robot_description_URL_REPOSITORY "")
set(my_robot_description_DEPRECATED "")