# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/msg/BagfileProgress.msg;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/msg/HistogramBucket.msg;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/msg/LandmarkEntry.msg;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/msg/LandmarkList.msg;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/msg/MetricFamily.msg;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/msg/MetricLabel.msg;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/msg/Metric.msg;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/msg/StatusCode.msg;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/msg/StatusResponse.msg;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/msg/SubmapEntry.msg;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/msg/SubmapList.msg;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/msg/SubmapTexture.msg;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/msg/TrajectoryStates.msg"
services_str = "/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/srv/FinishTrajectory.srv;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/srv/GetTrajectoryStates.srv;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/srv/ReadMetrics.srv;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/srv/StartTrajectory.srv;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/srv/SubmapQuery.srv;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/srv/TrajectoryQuery.srv;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/srv/WriteState.srv"
pkg_name = "cartographer_ros_msgs"
dependencies_str = "geometry_msgs;std_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "cartographer_ros_msgs;/root/rplidar_ws/src/cartographer_ros/cartographer_ros_msgs/msg;geometry_msgs;/opt/ros/melodic/share/geometry_msgs/cmake/../msg;std_msgs;/opt/ros/melodic/share/std_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python2"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/melodic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
