#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/CHANGELOG.rst
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/CMakeLists.txt
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/cartographer_rviz
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/cartographer_rviz/.clang-format
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/cartographer_rviz/drawable_submap.cc
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/cartographer_rviz/drawable_submap.h
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/cartographer_rviz/ogre_slice.cc
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/cartographer_rviz/ogre_slice.h
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/cartographer_rviz/submaps_display.cc
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/cartographer_rviz/submaps_display.h
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/ogre_media
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/ogre_media/materials
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/ogre_media/materials/glsl120
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/ogre_media/materials/glsl120/glsl120.program
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/ogre_media/materials/glsl120/submap.frag
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/ogre_media/materials/glsl120/submap.vert
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/ogre_media/materials/scripts
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/ogre_media/materials/scripts/submap.material
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/package.xml
#/root/rplidar_ws/src/cartographer_ros/cartographer_rviz/rviz_plugin_description.xml
